[project]
name = "project"
version = "0.1.0"
description = "Project for the course MSGAI"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["diffusion"]
